	pcie_system u0 (
		.pcie1_refclk_clk              (<connected-to-pcie1_refclk_clk>),              //     pcie1_refclk.clk
		.pcie1_npor_npor               (<connected-to-pcie1_npor_npor>),               //       pcie1_npor.npor
		.pcie1_npor_pin_perst          (<connected-to-pcie1_npor_pin_perst>),          //                 .pin_perst
		.clk_125_clk                   (<connected-to-clk_125_clk>),                   //          clk_125.clk
		.rst_125_reset_n               (<connected-to-rst_125_reset_n>),               //          rst_125.reset_n
		.pcie1_hip_ctrl_test_in        (<connected-to-pcie1_hip_ctrl_test_in>),        //   pcie1_hip_ctrl.test_in
		.pcie1_hip_ctrl_simu_mode_pipe (<connected-to-pcie1_hip_ctrl_simu_mode_pipe>), //                 .simu_mode_pipe
		.pcie1_hip_serial_rx_in0       (<connected-to-pcie1_hip_serial_rx_in0>),       // pcie1_hip_serial.rx_in0
		.pcie1_hip_serial_rx_in1       (<connected-to-pcie1_hip_serial_rx_in1>),       //                 .rx_in1
		.pcie1_hip_serial_rx_in2       (<connected-to-pcie1_hip_serial_rx_in2>),       //                 .rx_in2
		.pcie1_hip_serial_rx_in3       (<connected-to-pcie1_hip_serial_rx_in3>),       //                 .rx_in3
		.pcie1_hip_serial_rx_in4       (<connected-to-pcie1_hip_serial_rx_in4>),       //                 .rx_in4
		.pcie1_hip_serial_rx_in5       (<connected-to-pcie1_hip_serial_rx_in5>),       //                 .rx_in5
		.pcie1_hip_serial_rx_in6       (<connected-to-pcie1_hip_serial_rx_in6>),       //                 .rx_in6
		.pcie1_hip_serial_rx_in7       (<connected-to-pcie1_hip_serial_rx_in7>),       //                 .rx_in7
		.pcie1_hip_serial_tx_out0      (<connected-to-pcie1_hip_serial_tx_out0>),      //                 .tx_out0
		.pcie1_hip_serial_tx_out1      (<connected-to-pcie1_hip_serial_tx_out1>),      //                 .tx_out1
		.pcie1_hip_serial_tx_out2      (<connected-to-pcie1_hip_serial_tx_out2>),      //                 .tx_out2
		.pcie1_hip_serial_tx_out3      (<connected-to-pcie1_hip_serial_tx_out3>),      //                 .tx_out3
		.pcie1_hip_serial_tx_out4      (<connected-to-pcie1_hip_serial_tx_out4>),      //                 .tx_out4
		.pcie1_hip_serial_tx_out5      (<connected-to-pcie1_hip_serial_tx_out5>),      //                 .tx_out5
		.pcie1_hip_serial_tx_out6      (<connected-to-pcie1_hip_serial_tx_out6>),      //                 .tx_out6
		.pcie1_hip_serial_tx_out7      (<connected-to-pcie1_hip_serial_tx_out7>),      //                 .tx_out7
		.pcie2_refclk_clk              (<connected-to-pcie2_refclk_clk>),              //     pcie2_refclk.clk
		.pcie2_npor_npor               (<connected-to-pcie2_npor_npor>),               //       pcie2_npor.npor
		.pcie2_npor_pin_perst          (<connected-to-pcie2_npor_pin_perst>),          //                 .pin_perst
		.pcie2_hip_serial_rx_in0       (<connected-to-pcie2_hip_serial_rx_in0>),       // pcie2_hip_serial.rx_in0
		.pcie2_hip_serial_rx_in1       (<connected-to-pcie2_hip_serial_rx_in1>),       //                 .rx_in1
		.pcie2_hip_serial_rx_in2       (<connected-to-pcie2_hip_serial_rx_in2>),       //                 .rx_in2
		.pcie2_hip_serial_rx_in3       (<connected-to-pcie2_hip_serial_rx_in3>),       //                 .rx_in3
		.pcie2_hip_serial_rx_in4       (<connected-to-pcie2_hip_serial_rx_in4>),       //                 .rx_in4
		.pcie2_hip_serial_rx_in5       (<connected-to-pcie2_hip_serial_rx_in5>),       //                 .rx_in5
		.pcie2_hip_serial_rx_in6       (<connected-to-pcie2_hip_serial_rx_in6>),       //                 .rx_in6
		.pcie2_hip_serial_rx_in7       (<connected-to-pcie2_hip_serial_rx_in7>),       //                 .rx_in7
		.pcie2_hip_serial_tx_out0      (<connected-to-pcie2_hip_serial_tx_out0>),      //                 .tx_out0
		.pcie2_hip_serial_tx_out1      (<connected-to-pcie2_hip_serial_tx_out1>),      //                 .tx_out1
		.pcie2_hip_serial_tx_out2      (<connected-to-pcie2_hip_serial_tx_out2>),      //                 .tx_out2
		.pcie2_hip_serial_tx_out3      (<connected-to-pcie2_hip_serial_tx_out3>),      //                 .tx_out3
		.pcie2_hip_serial_tx_out4      (<connected-to-pcie2_hip_serial_tx_out4>),      //                 .tx_out4
		.pcie2_hip_serial_tx_out5      (<connected-to-pcie2_hip_serial_tx_out5>),      //                 .tx_out5
		.pcie2_hip_serial_tx_out6      (<connected-to-pcie2_hip_serial_tx_out6>),      //                 .tx_out6
		.pcie2_hip_serial_tx_out7      (<connected-to-pcie2_hip_serial_tx_out7>),      //                 .tx_out7
		.pcie2_hip_ctrl_test_in        (<connected-to-pcie2_hip_ctrl_test_in>),        //   pcie2_hip_ctrl.test_in
		.pcie2_hip_ctrl_simu_mode_pipe (<connected-to-pcie2_hip_ctrl_simu_mode_pipe>), //                 .simu_mode_pipe
		.uart_conduit_rxd              (<connected-to-uart_conduit_rxd>),              //     uart_conduit.rxd
		.uart_conduit_txd              (<connected-to-uart_conduit_txd>)               //                 .txd
	);

