// vroom_system_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 23.1 993

`timescale 1 ps / 1 ps
module vroom_system_mm_interconnect_0 (
		input  wire        pll_0_outclk0_clk,                              //                            pll_0_outclk0.clk
		input  wire        VROOM_0_reset_sink_reset_bridge_in_reset_reset, // VROOM_0_reset_sink_reset_bridge_in_reset.reset
		input  wire [31:0] VROOM_0_avalon_master_address,                  //                    VROOM_0_avalon_master.address
		output wire        VROOM_0_avalon_master_waitrequest,              //                                         .waitrequest
		input  wire [4:0]  VROOM_0_avalon_master_burstcount,               //                                         .burstcount
		input  wire [3:0]  VROOM_0_avalon_master_byteenable,               //                                         .byteenable
		input  wire        VROOM_0_avalon_master_read,                     //                                         .read
		output wire [31:0] VROOM_0_avalon_master_readdata,                 //                                         .readdata
		output wire        VROOM_0_avalon_master_readdatavalid,            //                                         .readdatavalid
		input  wire        VROOM_0_avalon_master_write,                    //                                         .write
		input  wire [31:0] VROOM_0_avalon_master_writedata,                //                                         .writedata
		output wire [1:0]  VROOM_0_avalon_master_response,                 //                                         .response
		output wire        VROOM_0_avalon_master_writeresponsevalid,       //                                         .writeresponsevalid
		output wire [12:0] RAM_s1_address,                                 //                                   RAM_s1.address
		output wire        RAM_s1_write,                                   //                                         .write
		input  wire [31:0] RAM_s1_readdata,                                //                                         .readdata
		output wire [31:0] RAM_s1_writedata,                               //                                         .writedata
		output wire [3:0]  RAM_s1_byteenable,                              //                                         .byteenable
		output wire        RAM_s1_chipselect,                              //                                         .chipselect
		output wire        RAM_s1_clken,                                   //                                         .clken
		output wire [14:0] ROM_s1_address,                                 //                                   ROM_s1.address
		output wire        ROM_s1_write,                                   //                                         .write
		input  wire [31:0] ROM_s1_readdata,                                //                                         .readdata
		output wire [31:0] ROM_s1_writedata,                               //                                         .writedata
		output wire [3:0]  ROM_s1_byteenable,                              //                                         .byteenable
		output wire        ROM_s1_chipselect,                              //                                         .chipselect
		output wire        ROM_s1_clken,                                   //                                         .clken
		output wire        ROM_s1_debugaccess                              //                                         .debugaccess
	);

	wire          vroom_0_avalon_master_translator_avalon_universal_master_0_debugaccess;        // VROOM_0_avalon_master_translator:uav_debugaccess -> VROOM_0_avalon_master_agent:av_debugaccess
	wire   [31:0] vroom_0_avalon_master_translator_avalon_universal_master_0_address;            // VROOM_0_avalon_master_translator:uav_address -> VROOM_0_avalon_master_agent:av_address
	wire          vroom_0_avalon_master_translator_avalon_universal_master_0_read;               // VROOM_0_avalon_master_translator:uav_read -> VROOM_0_avalon_master_agent:av_read
	wire    [3:0] vroom_0_avalon_master_translator_avalon_universal_master_0_byteenable;         // VROOM_0_avalon_master_translator:uav_byteenable -> VROOM_0_avalon_master_agent:av_byteenable
	wire          vroom_0_avalon_master_translator_avalon_universal_master_0_readdatavalid;      // VROOM_0_avalon_master_agent:av_readdatavalid -> VROOM_0_avalon_master_translator:uav_readdatavalid
	wire          vroom_0_avalon_master_translator_avalon_universal_master_0_waitrequest;        // VROOM_0_avalon_master_agent:av_waitrequest -> VROOM_0_avalon_master_translator:uav_waitrequest
	wire   [31:0] vroom_0_avalon_master_translator_avalon_universal_master_0_readdata;           // VROOM_0_avalon_master_agent:av_readdata -> VROOM_0_avalon_master_translator:uav_readdata
	wire    [1:0] vroom_0_avalon_master_translator_avalon_universal_master_0_response;           // VROOM_0_avalon_master_agent:av_response -> VROOM_0_avalon_master_translator:uav_response
	wire          vroom_0_avalon_master_translator_avalon_universal_master_0_lock;               // VROOM_0_avalon_master_translator:uav_lock -> VROOM_0_avalon_master_agent:av_lock
	wire          vroom_0_avalon_master_translator_avalon_universal_master_0_write;              // VROOM_0_avalon_master_translator:uav_write -> VROOM_0_avalon_master_agent:av_write
	wire   [31:0] vroom_0_avalon_master_translator_avalon_universal_master_0_writedata;          // VROOM_0_avalon_master_translator:uav_writedata -> VROOM_0_avalon_master_agent:av_writedata
	wire          vroom_0_avalon_master_translator_avalon_universal_master_0_writeresponsevalid; // VROOM_0_avalon_master_agent:av_writeresponsevalid -> VROOM_0_avalon_master_translator:uav_writeresponsevalid
	wire    [6:0] vroom_0_avalon_master_translator_avalon_universal_master_0_burstcount;         // VROOM_0_avalon_master_translator:uav_burstcount -> VROOM_0_avalon_master_agent:av_burstcount
	wire   [31:0] rom_s1_agent_m0_readdata;                                                      // ROM_s1_translator:uav_readdata -> ROM_s1_agent:m0_readdata
	wire          rom_s1_agent_m0_waitrequest;                                                   // ROM_s1_translator:uav_waitrequest -> ROM_s1_agent:m0_waitrequest
	wire          rom_s1_agent_m0_debugaccess;                                                   // ROM_s1_agent:m0_debugaccess -> ROM_s1_translator:uav_debugaccess
	wire   [31:0] rom_s1_agent_m0_address;                                                       // ROM_s1_agent:m0_address -> ROM_s1_translator:uav_address
	wire    [3:0] rom_s1_agent_m0_byteenable;                                                    // ROM_s1_agent:m0_byteenable -> ROM_s1_translator:uav_byteenable
	wire          rom_s1_agent_m0_read;                                                          // ROM_s1_agent:m0_read -> ROM_s1_translator:uav_read
	wire          rom_s1_agent_m0_readdatavalid;                                                 // ROM_s1_translator:uav_readdatavalid -> ROM_s1_agent:m0_readdatavalid
	wire          rom_s1_agent_m0_lock;                                                          // ROM_s1_agent:m0_lock -> ROM_s1_translator:uav_lock
	wire   [31:0] rom_s1_agent_m0_writedata;                                                     // ROM_s1_agent:m0_writedata -> ROM_s1_translator:uav_writedata
	wire          rom_s1_agent_m0_write;                                                         // ROM_s1_agent:m0_write -> ROM_s1_translator:uav_write
	wire    [2:0] rom_s1_agent_m0_burstcount;                                                    // ROM_s1_agent:m0_burstcount -> ROM_s1_translator:uav_burstcount
	wire          rom_s1_agent_rf_source_valid;                                                  // ROM_s1_agent:rf_source_valid -> ROM_s1_agent_rsp_fifo:in_valid
	wire  [106:0] rom_s1_agent_rf_source_data;                                                   // ROM_s1_agent:rf_source_data -> ROM_s1_agent_rsp_fifo:in_data
	wire          rom_s1_agent_rf_source_ready;                                                  // ROM_s1_agent_rsp_fifo:in_ready -> ROM_s1_agent:rf_source_ready
	wire          rom_s1_agent_rf_source_startofpacket;                                          // ROM_s1_agent:rf_source_startofpacket -> ROM_s1_agent_rsp_fifo:in_startofpacket
	wire          rom_s1_agent_rf_source_endofpacket;                                            // ROM_s1_agent:rf_source_endofpacket -> ROM_s1_agent_rsp_fifo:in_endofpacket
	wire          rom_s1_agent_rsp_fifo_out_valid;                                               // ROM_s1_agent_rsp_fifo:out_valid -> ROM_s1_agent:rf_sink_valid
	wire  [106:0] rom_s1_agent_rsp_fifo_out_data;                                                // ROM_s1_agent_rsp_fifo:out_data -> ROM_s1_agent:rf_sink_data
	wire          rom_s1_agent_rsp_fifo_out_ready;                                               // ROM_s1_agent:rf_sink_ready -> ROM_s1_agent_rsp_fifo:out_ready
	wire          rom_s1_agent_rsp_fifo_out_startofpacket;                                       // ROM_s1_agent_rsp_fifo:out_startofpacket -> ROM_s1_agent:rf_sink_startofpacket
	wire          rom_s1_agent_rsp_fifo_out_endofpacket;                                         // ROM_s1_agent_rsp_fifo:out_endofpacket -> ROM_s1_agent:rf_sink_endofpacket
	wire   [31:0] ram_s1_agent_m0_readdata;                                                      // RAM_s1_translator:uav_readdata -> RAM_s1_agent:m0_readdata
	wire          ram_s1_agent_m0_waitrequest;                                                   // RAM_s1_translator:uav_waitrequest -> RAM_s1_agent:m0_waitrequest
	wire          ram_s1_agent_m0_debugaccess;                                                   // RAM_s1_agent:m0_debugaccess -> RAM_s1_translator:uav_debugaccess
	wire   [31:0] ram_s1_agent_m0_address;                                                       // RAM_s1_agent:m0_address -> RAM_s1_translator:uav_address
	wire    [3:0] ram_s1_agent_m0_byteenable;                                                    // RAM_s1_agent:m0_byteenable -> RAM_s1_translator:uav_byteenable
	wire          ram_s1_agent_m0_read;                                                          // RAM_s1_agent:m0_read -> RAM_s1_translator:uav_read
	wire          ram_s1_agent_m0_readdatavalid;                                                 // RAM_s1_translator:uav_readdatavalid -> RAM_s1_agent:m0_readdatavalid
	wire          ram_s1_agent_m0_lock;                                                          // RAM_s1_agent:m0_lock -> RAM_s1_translator:uav_lock
	wire   [31:0] ram_s1_agent_m0_writedata;                                                     // RAM_s1_agent:m0_writedata -> RAM_s1_translator:uav_writedata
	wire          ram_s1_agent_m0_write;                                                         // RAM_s1_agent:m0_write -> RAM_s1_translator:uav_write
	wire    [2:0] ram_s1_agent_m0_burstcount;                                                    // RAM_s1_agent:m0_burstcount -> RAM_s1_translator:uav_burstcount
	wire          ram_s1_agent_rf_source_valid;                                                  // RAM_s1_agent:rf_source_valid -> RAM_s1_agent_rsp_fifo:in_valid
	wire  [106:0] ram_s1_agent_rf_source_data;                                                   // RAM_s1_agent:rf_source_data -> RAM_s1_agent_rsp_fifo:in_data
	wire          ram_s1_agent_rf_source_ready;                                                  // RAM_s1_agent_rsp_fifo:in_ready -> RAM_s1_agent:rf_source_ready
	wire          ram_s1_agent_rf_source_startofpacket;                                          // RAM_s1_agent:rf_source_startofpacket -> RAM_s1_agent_rsp_fifo:in_startofpacket
	wire          ram_s1_agent_rf_source_endofpacket;                                            // RAM_s1_agent:rf_source_endofpacket -> RAM_s1_agent_rsp_fifo:in_endofpacket
	wire          ram_s1_agent_rsp_fifo_out_valid;                                               // RAM_s1_agent_rsp_fifo:out_valid -> RAM_s1_agent:rf_sink_valid
	wire  [106:0] ram_s1_agent_rsp_fifo_out_data;                                                // RAM_s1_agent_rsp_fifo:out_data -> RAM_s1_agent:rf_sink_data
	wire          ram_s1_agent_rsp_fifo_out_ready;                                               // RAM_s1_agent:rf_sink_ready -> RAM_s1_agent_rsp_fifo:out_ready
	wire          ram_s1_agent_rsp_fifo_out_startofpacket;                                       // RAM_s1_agent_rsp_fifo:out_startofpacket -> RAM_s1_agent:rf_sink_startofpacket
	wire          ram_s1_agent_rsp_fifo_out_endofpacket;                                         // RAM_s1_agent_rsp_fifo:out_endofpacket -> RAM_s1_agent:rf_sink_endofpacket
	wire          vroom_0_avalon_master_agent_cp_valid;                                          // VROOM_0_avalon_master_agent:cp_valid -> router:sink_valid
	wire  [105:0] vroom_0_avalon_master_agent_cp_data;                                           // VROOM_0_avalon_master_agent:cp_data -> router:sink_data
	wire          vroom_0_avalon_master_agent_cp_ready;                                          // router:sink_ready -> VROOM_0_avalon_master_agent:cp_ready
	wire          vroom_0_avalon_master_agent_cp_startofpacket;                                  // VROOM_0_avalon_master_agent:cp_startofpacket -> router:sink_startofpacket
	wire          vroom_0_avalon_master_agent_cp_endofpacket;                                    // VROOM_0_avalon_master_agent:cp_endofpacket -> router:sink_endofpacket
	wire          rom_s1_agent_rp_valid;                                                         // ROM_s1_agent:rp_valid -> router_001:sink_valid
	wire  [105:0] rom_s1_agent_rp_data;                                                          // ROM_s1_agent:rp_data -> router_001:sink_data
	wire          rom_s1_agent_rp_ready;                                                         // router_001:sink_ready -> ROM_s1_agent:rp_ready
	wire          rom_s1_agent_rp_startofpacket;                                                 // ROM_s1_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire          rom_s1_agent_rp_endofpacket;                                                   // ROM_s1_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                                                          // router_001:src_valid -> rsp_demux:sink_valid
	wire  [105:0] router_001_src_data;                                                           // router_001:src_data -> rsp_demux:sink_data
	wire          router_001_src_ready;                                                          // rsp_demux:sink_ready -> router_001:src_ready
	wire    [1:0] router_001_src_channel;                                                        // router_001:src_channel -> rsp_demux:sink_channel
	wire          router_001_src_startofpacket;                                                  // router_001:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_001_src_endofpacket;                                                    // router_001:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          ram_s1_agent_rp_valid;                                                         // RAM_s1_agent:rp_valid -> router_002:sink_valid
	wire  [105:0] ram_s1_agent_rp_data;                                                          // RAM_s1_agent:rp_data -> router_002:sink_data
	wire          ram_s1_agent_rp_ready;                                                         // router_002:sink_ready -> RAM_s1_agent:rp_ready
	wire          ram_s1_agent_rp_startofpacket;                                                 // RAM_s1_agent:rp_startofpacket -> router_002:sink_startofpacket
	wire          ram_s1_agent_rp_endofpacket;                                                   // RAM_s1_agent:rp_endofpacket -> router_002:sink_endofpacket
	wire          router_002_src_valid;                                                          // router_002:src_valid -> rsp_demux_001:sink_valid
	wire  [105:0] router_002_src_data;                                                           // router_002:src_data -> rsp_demux_001:sink_data
	wire          router_002_src_ready;                                                          // rsp_demux_001:sink_ready -> router_002:src_ready
	wire    [1:0] router_002_src_channel;                                                        // router_002:src_channel -> rsp_demux_001:sink_channel
	wire          router_002_src_startofpacket;                                                  // router_002:src_startofpacket -> rsp_demux_001:sink_startofpacket
	wire          router_002_src_endofpacket;                                                    // router_002:src_endofpacket -> rsp_demux_001:sink_endofpacket
	wire          router_src_valid;                                                              // router:src_valid -> VROOM_0_avalon_master_limiter:cmd_sink_valid
	wire  [105:0] router_src_data;                                                               // router:src_data -> VROOM_0_avalon_master_limiter:cmd_sink_data
	wire          router_src_ready;                                                              // VROOM_0_avalon_master_limiter:cmd_sink_ready -> router:src_ready
	wire    [1:0] router_src_channel;                                                            // router:src_channel -> VROOM_0_avalon_master_limiter:cmd_sink_channel
	wire          router_src_startofpacket;                                                      // router:src_startofpacket -> VROOM_0_avalon_master_limiter:cmd_sink_startofpacket
	wire          router_src_endofpacket;                                                        // router:src_endofpacket -> VROOM_0_avalon_master_limiter:cmd_sink_endofpacket
	wire  [105:0] vroom_0_avalon_master_limiter_cmd_src_data;                                    // VROOM_0_avalon_master_limiter:cmd_src_data -> cmd_demux:sink_data
	wire          vroom_0_avalon_master_limiter_cmd_src_ready;                                   // cmd_demux:sink_ready -> VROOM_0_avalon_master_limiter:cmd_src_ready
	wire    [1:0] vroom_0_avalon_master_limiter_cmd_src_channel;                                 // VROOM_0_avalon_master_limiter:cmd_src_channel -> cmd_demux:sink_channel
	wire          vroom_0_avalon_master_limiter_cmd_src_startofpacket;                           // VROOM_0_avalon_master_limiter:cmd_src_startofpacket -> cmd_demux:sink_startofpacket
	wire          vroom_0_avalon_master_limiter_cmd_src_endofpacket;                             // VROOM_0_avalon_master_limiter:cmd_src_endofpacket -> cmd_demux:sink_endofpacket
	wire          rsp_mux_src_valid;                                                             // rsp_mux:src_valid -> VROOM_0_avalon_master_limiter:rsp_sink_valid
	wire  [105:0] rsp_mux_src_data;                                                              // rsp_mux:src_data -> VROOM_0_avalon_master_limiter:rsp_sink_data
	wire          rsp_mux_src_ready;                                                             // VROOM_0_avalon_master_limiter:rsp_sink_ready -> rsp_mux:src_ready
	wire    [1:0] rsp_mux_src_channel;                                                           // rsp_mux:src_channel -> VROOM_0_avalon_master_limiter:rsp_sink_channel
	wire          rsp_mux_src_startofpacket;                                                     // rsp_mux:src_startofpacket -> VROOM_0_avalon_master_limiter:rsp_sink_startofpacket
	wire          rsp_mux_src_endofpacket;                                                       // rsp_mux:src_endofpacket -> VROOM_0_avalon_master_limiter:rsp_sink_endofpacket
	wire          vroom_0_avalon_master_limiter_rsp_src_valid;                                   // VROOM_0_avalon_master_limiter:rsp_src_valid -> VROOM_0_avalon_master_agent:rp_valid
	wire  [105:0] vroom_0_avalon_master_limiter_rsp_src_data;                                    // VROOM_0_avalon_master_limiter:rsp_src_data -> VROOM_0_avalon_master_agent:rp_data
	wire          vroom_0_avalon_master_limiter_rsp_src_ready;                                   // VROOM_0_avalon_master_agent:rp_ready -> VROOM_0_avalon_master_limiter:rsp_src_ready
	wire    [1:0] vroom_0_avalon_master_limiter_rsp_src_channel;                                 // VROOM_0_avalon_master_limiter:rsp_src_channel -> VROOM_0_avalon_master_agent:rp_channel
	wire          vroom_0_avalon_master_limiter_rsp_src_startofpacket;                           // VROOM_0_avalon_master_limiter:rsp_src_startofpacket -> VROOM_0_avalon_master_agent:rp_startofpacket
	wire          vroom_0_avalon_master_limiter_rsp_src_endofpacket;                             // VROOM_0_avalon_master_limiter:rsp_src_endofpacket -> VROOM_0_avalon_master_agent:rp_endofpacket
	wire          cmd_mux_src_valid;                                                             // cmd_mux:src_valid -> ROM_s1_burst_adapter:sink0_valid
	wire  [105:0] cmd_mux_src_data;                                                              // cmd_mux:src_data -> ROM_s1_burst_adapter:sink0_data
	wire          cmd_mux_src_ready;                                                             // ROM_s1_burst_adapter:sink0_ready -> cmd_mux:src_ready
	wire    [1:0] cmd_mux_src_channel;                                                           // cmd_mux:src_channel -> ROM_s1_burst_adapter:sink0_channel
	wire          cmd_mux_src_startofpacket;                                                     // cmd_mux:src_startofpacket -> ROM_s1_burst_adapter:sink0_startofpacket
	wire          cmd_mux_src_endofpacket;                                                       // cmd_mux:src_endofpacket -> ROM_s1_burst_adapter:sink0_endofpacket
	wire          rom_s1_burst_adapter_source0_valid;                                            // ROM_s1_burst_adapter:source0_valid -> ROM_s1_agent:cp_valid
	wire  [105:0] rom_s1_burst_adapter_source0_data;                                             // ROM_s1_burst_adapter:source0_data -> ROM_s1_agent:cp_data
	wire          rom_s1_burst_adapter_source0_ready;                                            // ROM_s1_agent:cp_ready -> ROM_s1_burst_adapter:source0_ready
	wire    [1:0] rom_s1_burst_adapter_source0_channel;                                          // ROM_s1_burst_adapter:source0_channel -> ROM_s1_agent:cp_channel
	wire          rom_s1_burst_adapter_source0_startofpacket;                                    // ROM_s1_burst_adapter:source0_startofpacket -> ROM_s1_agent:cp_startofpacket
	wire          rom_s1_burst_adapter_source0_endofpacket;                                      // ROM_s1_burst_adapter:source0_endofpacket -> ROM_s1_agent:cp_endofpacket
	wire          cmd_mux_001_src_valid;                                                         // cmd_mux_001:src_valid -> RAM_s1_burst_adapter:sink0_valid
	wire  [105:0] cmd_mux_001_src_data;                                                          // cmd_mux_001:src_data -> RAM_s1_burst_adapter:sink0_data
	wire          cmd_mux_001_src_ready;                                                         // RAM_s1_burst_adapter:sink0_ready -> cmd_mux_001:src_ready
	wire    [1:0] cmd_mux_001_src_channel;                                                       // cmd_mux_001:src_channel -> RAM_s1_burst_adapter:sink0_channel
	wire          cmd_mux_001_src_startofpacket;                                                 // cmd_mux_001:src_startofpacket -> RAM_s1_burst_adapter:sink0_startofpacket
	wire          cmd_mux_001_src_endofpacket;                                                   // cmd_mux_001:src_endofpacket -> RAM_s1_burst_adapter:sink0_endofpacket
	wire          ram_s1_burst_adapter_source0_valid;                                            // RAM_s1_burst_adapter:source0_valid -> RAM_s1_agent:cp_valid
	wire  [105:0] ram_s1_burst_adapter_source0_data;                                             // RAM_s1_burst_adapter:source0_data -> RAM_s1_agent:cp_data
	wire          ram_s1_burst_adapter_source0_ready;                                            // RAM_s1_agent:cp_ready -> RAM_s1_burst_adapter:source0_ready
	wire    [1:0] ram_s1_burst_adapter_source0_channel;                                          // RAM_s1_burst_adapter:source0_channel -> RAM_s1_agent:cp_channel
	wire          ram_s1_burst_adapter_source0_startofpacket;                                    // RAM_s1_burst_adapter:source0_startofpacket -> RAM_s1_agent:cp_startofpacket
	wire          ram_s1_burst_adapter_source0_endofpacket;                                      // RAM_s1_burst_adapter:source0_endofpacket -> RAM_s1_agent:cp_endofpacket
	wire          cmd_demux_src0_valid;                                                          // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [105:0] cmd_demux_src0_data;                                                           // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                                          // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [1:0] cmd_demux_src0_channel;                                                        // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                                  // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                                    // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          cmd_demux_src1_valid;                                                          // cmd_demux:src1_valid -> cmd_mux_001:sink0_valid
	wire  [105:0] cmd_demux_src1_data;                                                           // cmd_demux:src1_data -> cmd_mux_001:sink0_data
	wire          cmd_demux_src1_ready;                                                          // cmd_mux_001:sink0_ready -> cmd_demux:src1_ready
	wire    [1:0] cmd_demux_src1_channel;                                                        // cmd_demux:src1_channel -> cmd_mux_001:sink0_channel
	wire          cmd_demux_src1_startofpacket;                                                  // cmd_demux:src1_startofpacket -> cmd_mux_001:sink0_startofpacket
	wire          cmd_demux_src1_endofpacket;                                                    // cmd_demux:src1_endofpacket -> cmd_mux_001:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                                          // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [105:0] rsp_demux_src0_data;                                                           // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                                          // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [1:0] rsp_demux_src0_channel;                                                        // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                                  // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                                    // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire          rsp_demux_001_src0_valid;                                                      // rsp_demux_001:src0_valid -> rsp_mux:sink1_valid
	wire  [105:0] rsp_demux_001_src0_data;                                                       // rsp_demux_001:src0_data -> rsp_mux:sink1_data
	wire          rsp_demux_001_src0_ready;                                                      // rsp_mux:sink1_ready -> rsp_demux_001:src0_ready
	wire    [1:0] rsp_demux_001_src0_channel;                                                    // rsp_demux_001:src0_channel -> rsp_mux:sink1_channel
	wire          rsp_demux_001_src0_startofpacket;                                              // rsp_demux_001:src0_startofpacket -> rsp_mux:sink1_startofpacket
	wire          rsp_demux_001_src0_endofpacket;                                                // rsp_demux_001:src0_endofpacket -> rsp_mux:sink1_endofpacket
	wire    [1:0] vroom_0_avalon_master_limiter_cmd_valid_data;                                  // VROOM_0_avalon_master_limiter:cmd_src_valid -> cmd_demux:sink_valid
	wire          rom_s1_agent_rdata_fifo_src_valid;                                             // ROM_s1_agent:rdata_fifo_src_valid -> avalon_st_adapter:in_0_valid
	wire   [33:0] rom_s1_agent_rdata_fifo_src_data;                                              // ROM_s1_agent:rdata_fifo_src_data -> avalon_st_adapter:in_0_data
	wire          rom_s1_agent_rdata_fifo_src_ready;                                             // avalon_st_adapter:in_0_ready -> ROM_s1_agent:rdata_fifo_src_ready
	wire          avalon_st_adapter_out_0_valid;                                                 // avalon_st_adapter:out_0_valid -> ROM_s1_agent:rdata_fifo_sink_valid
	wire   [33:0] avalon_st_adapter_out_0_data;                                                  // avalon_st_adapter:out_0_data -> ROM_s1_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_out_0_ready;                                                 // ROM_s1_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire    [0:0] avalon_st_adapter_out_0_error;                                                 // avalon_st_adapter:out_0_error -> ROM_s1_agent:rdata_fifo_sink_error
	wire          ram_s1_agent_rdata_fifo_src_valid;                                             // RAM_s1_agent:rdata_fifo_src_valid -> avalon_st_adapter_001:in_0_valid
	wire   [33:0] ram_s1_agent_rdata_fifo_src_data;                                              // RAM_s1_agent:rdata_fifo_src_data -> avalon_st_adapter_001:in_0_data
	wire          ram_s1_agent_rdata_fifo_src_ready;                                             // avalon_st_adapter_001:in_0_ready -> RAM_s1_agent:rdata_fifo_src_ready
	wire          avalon_st_adapter_001_out_0_valid;                                             // avalon_st_adapter_001:out_0_valid -> RAM_s1_agent:rdata_fifo_sink_valid
	wire   [33:0] avalon_st_adapter_001_out_0_data;                                              // avalon_st_adapter_001:out_0_data -> RAM_s1_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_001_out_0_ready;                                             // RAM_s1_agent:rdata_fifo_sink_ready -> avalon_st_adapter_001:out_0_ready
	wire    [0:0] avalon_st_adapter_001_out_0_error;                                             // avalon_st_adapter_001:out_0_error -> RAM_s1_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (5),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (7),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (1),
		.USE_WRITERESPONSE           (1),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) vroom_0_avalon_master_translator (
		.clk                    (pll_0_outclk0_clk),                                                             //                       clk.clk
		.reset                  (VROOM_0_reset_sink_reset_bridge_in_reset_reset),                                //                     reset.reset
		.uav_address            (vroom_0_avalon_master_translator_avalon_universal_master_0_address),            // avalon_universal_master_0.address
		.uav_burstcount         (vroom_0_avalon_master_translator_avalon_universal_master_0_burstcount),         //                          .burstcount
		.uav_read               (vroom_0_avalon_master_translator_avalon_universal_master_0_read),               //                          .read
		.uav_write              (vroom_0_avalon_master_translator_avalon_universal_master_0_write),              //                          .write
		.uav_waitrequest        (vroom_0_avalon_master_translator_avalon_universal_master_0_waitrequest),        //                          .waitrequest
		.uav_readdatavalid      (vroom_0_avalon_master_translator_avalon_universal_master_0_readdatavalid),      //                          .readdatavalid
		.uav_byteenable         (vroom_0_avalon_master_translator_avalon_universal_master_0_byteenable),         //                          .byteenable
		.uav_readdata           (vroom_0_avalon_master_translator_avalon_universal_master_0_readdata),           //                          .readdata
		.uav_writedata          (vroom_0_avalon_master_translator_avalon_universal_master_0_writedata),          //                          .writedata
		.uav_lock               (vroom_0_avalon_master_translator_avalon_universal_master_0_lock),               //                          .lock
		.uav_debugaccess        (vroom_0_avalon_master_translator_avalon_universal_master_0_debugaccess),        //                          .debugaccess
		.uav_response           (vroom_0_avalon_master_translator_avalon_universal_master_0_response),           //                          .response
		.uav_writeresponsevalid (vroom_0_avalon_master_translator_avalon_universal_master_0_writeresponsevalid), //                          .writeresponsevalid
		.av_address             (VROOM_0_avalon_master_address),                                                 //      avalon_anti_master_0.address
		.av_waitrequest         (VROOM_0_avalon_master_waitrequest),                                             //                          .waitrequest
		.av_burstcount          (VROOM_0_avalon_master_burstcount),                                              //                          .burstcount
		.av_byteenable          (VROOM_0_avalon_master_byteenable),                                              //                          .byteenable
		.av_read                (VROOM_0_avalon_master_read),                                                    //                          .read
		.av_readdata            (VROOM_0_avalon_master_readdata),                                                //                          .readdata
		.av_readdatavalid       (VROOM_0_avalon_master_readdatavalid),                                           //                          .readdatavalid
		.av_write               (VROOM_0_avalon_master_write),                                                   //                          .write
		.av_writedata           (VROOM_0_avalon_master_writedata),                                               //                          .writedata
		.av_response            (VROOM_0_avalon_master_response),                                                //                          .response
		.av_writeresponsevalid  (VROOM_0_avalon_master_writeresponsevalid),                                      //                          .writeresponsevalid
		.av_beginbursttransfer  (1'b0),                                                                          //               (terminated)
		.av_begintransfer       (1'b0),                                                                          //               (terminated)
		.av_chipselect          (1'b0),                                                                          //               (terminated)
		.av_lock                (1'b0),                                                                          //               (terminated)
		.av_debugaccess         (1'b0),                                                                          //               (terminated)
		.uav_clken              (),                                                                              //               (terminated)
		.av_clken               (1'b1)                                                                           //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (15),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) rom_s1_translator (
		.clk                    (pll_0_outclk0_clk),                              //                      clk.clk
		.reset                  (VROOM_0_reset_sink_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (rom_s1_agent_m0_address),                        // avalon_universal_slave_0.address
		.uav_burstcount         (rom_s1_agent_m0_burstcount),                     //                         .burstcount
		.uav_read               (rom_s1_agent_m0_read),                           //                         .read
		.uav_write              (rom_s1_agent_m0_write),                          //                         .write
		.uav_waitrequest        (rom_s1_agent_m0_waitrequest),                    //                         .waitrequest
		.uav_readdatavalid      (rom_s1_agent_m0_readdatavalid),                  //                         .readdatavalid
		.uav_byteenable         (rom_s1_agent_m0_byteenable),                     //                         .byteenable
		.uav_readdata           (rom_s1_agent_m0_readdata),                       //                         .readdata
		.uav_writedata          (rom_s1_agent_m0_writedata),                      //                         .writedata
		.uav_lock               (rom_s1_agent_m0_lock),                           //                         .lock
		.uav_debugaccess        (rom_s1_agent_m0_debugaccess),                    //                         .debugaccess
		.av_address             (ROM_s1_address),                                 //      avalon_anti_slave_0.address
		.av_write               (ROM_s1_write),                                   //                         .write
		.av_readdata            (ROM_s1_readdata),                                //                         .readdata
		.av_writedata           (ROM_s1_writedata),                               //                         .writedata
		.av_byteenable          (ROM_s1_byteenable),                              //                         .byteenable
		.av_chipselect          (ROM_s1_chipselect),                              //                         .chipselect
		.av_clken               (ROM_s1_clken),                                   //                         .clken
		.av_debugaccess         (ROM_s1_debugaccess),                             //                         .debugaccess
		.av_read                (),                                               //              (terminated)
		.av_begintransfer       (),                                               //              (terminated)
		.av_beginbursttransfer  (),                                               //              (terminated)
		.av_burstcount          (),                                               //              (terminated)
		.av_readdatavalid       (1'b0),                                           //              (terminated)
		.av_waitrequest         (1'b0),                                           //              (terminated)
		.av_writebyteenable     (),                                               //              (terminated)
		.av_lock                (),                                               //              (terminated)
		.uav_clken              (1'b0),                                           //              (terminated)
		.av_outputenable        (),                                               //              (terminated)
		.uav_response           (),                                               //              (terminated)
		.av_response            (2'b00),                                          //              (terminated)
		.uav_writeresponsevalid (),                                               //              (terminated)
		.av_writeresponsevalid  (1'b0)                                            //              (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (13),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) ram_s1_translator (
		.clk                    (pll_0_outclk0_clk),                              //                      clk.clk
		.reset                  (VROOM_0_reset_sink_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (ram_s1_agent_m0_address),                        // avalon_universal_slave_0.address
		.uav_burstcount         (ram_s1_agent_m0_burstcount),                     //                         .burstcount
		.uav_read               (ram_s1_agent_m0_read),                           //                         .read
		.uav_write              (ram_s1_agent_m0_write),                          //                         .write
		.uav_waitrequest        (ram_s1_agent_m0_waitrequest),                    //                         .waitrequest
		.uav_readdatavalid      (ram_s1_agent_m0_readdatavalid),                  //                         .readdatavalid
		.uav_byteenable         (ram_s1_agent_m0_byteenable),                     //                         .byteenable
		.uav_readdata           (ram_s1_agent_m0_readdata),                       //                         .readdata
		.uav_writedata          (ram_s1_agent_m0_writedata),                      //                         .writedata
		.uav_lock               (ram_s1_agent_m0_lock),                           //                         .lock
		.uav_debugaccess        (ram_s1_agent_m0_debugaccess),                    //                         .debugaccess
		.av_address             (RAM_s1_address),                                 //      avalon_anti_slave_0.address
		.av_write               (RAM_s1_write),                                   //                         .write
		.av_readdata            (RAM_s1_readdata),                                //                         .readdata
		.av_writedata           (RAM_s1_writedata),                               //                         .writedata
		.av_byteenable          (RAM_s1_byteenable),                              //                         .byteenable
		.av_chipselect          (RAM_s1_chipselect),                              //                         .chipselect
		.av_clken               (RAM_s1_clken),                                   //                         .clken
		.av_read                (),                                               //              (terminated)
		.av_begintransfer       (),                                               //              (terminated)
		.av_beginbursttransfer  (),                                               //              (terminated)
		.av_burstcount          (),                                               //              (terminated)
		.av_readdatavalid       (1'b0),                                           //              (terminated)
		.av_waitrequest         (1'b0),                                           //              (terminated)
		.av_writebyteenable     (),                                               //              (terminated)
		.av_lock                (),                                               //              (terminated)
		.uav_clken              (1'b0),                                           //              (terminated)
		.av_debugaccess         (),                                               //              (terminated)
		.av_outputenable        (),                                               //              (terminated)
		.uav_response           (),                                               //              (terminated)
		.av_response            (2'b00),                                          //              (terminated)
		.uav_writeresponsevalid (),                                               //              (terminated)
		.av_writeresponsevalid  (1'b0)                                            //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (105),
		.PKT_ORI_BURST_SIZE_L      (103),
		.PKT_RESPONSE_STATUS_H     (102),
		.PKT_RESPONSE_STATUS_L     (101),
		.PKT_QOS_H                 (90),
		.PKT_QOS_L                 (90),
		.PKT_DATA_SIDEBAND_H       (88),
		.PKT_DATA_SIDEBAND_L       (88),
		.PKT_ADDR_SIDEBAND_H       (87),
		.PKT_ADDR_SIDEBAND_L       (87),
		.PKT_BURST_TYPE_H          (86),
		.PKT_BURST_TYPE_L          (85),
		.PKT_CACHE_H               (100),
		.PKT_CACHE_L               (97),
		.PKT_THREAD_ID_H           (93),
		.PKT_THREAD_ID_L           (93),
		.PKT_BURST_SIZE_H          (84),
		.PKT_BURST_SIZE_L          (82),
		.PKT_TRANS_EXCLUSIVE       (73),
		.PKT_TRANS_LOCK            (72),
		.PKT_BEGIN_BURST           (89),
		.PKT_PROTECTION_H          (96),
		.PKT_PROTECTION_L          (94),
		.PKT_BURSTWRAP_H           (81),
		.PKT_BURSTWRAP_L           (81),
		.PKT_BYTE_CNT_H            (80),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (91),
		.PKT_SRC_ID_L              (91),
		.PKT_DEST_ID_H             (92),
		.PKT_DEST_ID_L             (92),
		.ST_DATA_W                 (106),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (7),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (1),
		.USE_WRITERESPONSE         (1)
	) vroom_0_avalon_master_agent (
		.clk                   (pll_0_outclk0_clk),                                                             //       clk.clk
		.reset                 (VROOM_0_reset_sink_reset_bridge_in_reset_reset),                                // clk_reset.reset
		.av_address            (vroom_0_avalon_master_translator_avalon_universal_master_0_address),            //        av.address
		.av_write              (vroom_0_avalon_master_translator_avalon_universal_master_0_write),              //          .write
		.av_read               (vroom_0_avalon_master_translator_avalon_universal_master_0_read),               //          .read
		.av_writedata          (vroom_0_avalon_master_translator_avalon_universal_master_0_writedata),          //          .writedata
		.av_readdata           (vroom_0_avalon_master_translator_avalon_universal_master_0_readdata),           //          .readdata
		.av_waitrequest        (vroom_0_avalon_master_translator_avalon_universal_master_0_waitrequest),        //          .waitrequest
		.av_readdatavalid      (vroom_0_avalon_master_translator_avalon_universal_master_0_readdatavalid),      //          .readdatavalid
		.av_byteenable         (vroom_0_avalon_master_translator_avalon_universal_master_0_byteenable),         //          .byteenable
		.av_burstcount         (vroom_0_avalon_master_translator_avalon_universal_master_0_burstcount),         //          .burstcount
		.av_debugaccess        (vroom_0_avalon_master_translator_avalon_universal_master_0_debugaccess),        //          .debugaccess
		.av_lock               (vroom_0_avalon_master_translator_avalon_universal_master_0_lock),               //          .lock
		.av_response           (vroom_0_avalon_master_translator_avalon_universal_master_0_response),           //          .response
		.av_writeresponsevalid (vroom_0_avalon_master_translator_avalon_universal_master_0_writeresponsevalid), //          .writeresponsevalid
		.cp_valid              (vroom_0_avalon_master_agent_cp_valid),                                          //        cp.valid
		.cp_data               (vroom_0_avalon_master_agent_cp_data),                                           //          .data
		.cp_startofpacket      (vroom_0_avalon_master_agent_cp_startofpacket),                                  //          .startofpacket
		.cp_endofpacket        (vroom_0_avalon_master_agent_cp_endofpacket),                                    //          .endofpacket
		.cp_ready              (vroom_0_avalon_master_agent_cp_ready),                                          //          .ready
		.rp_valid              (vroom_0_avalon_master_limiter_rsp_src_valid),                                   //        rp.valid
		.rp_data               (vroom_0_avalon_master_limiter_rsp_src_data),                                    //          .data
		.rp_channel            (vroom_0_avalon_master_limiter_rsp_src_channel),                                 //          .channel
		.rp_startofpacket      (vroom_0_avalon_master_limiter_rsp_src_startofpacket),                           //          .startofpacket
		.rp_endofpacket        (vroom_0_avalon_master_limiter_rsp_src_endofpacket),                             //          .endofpacket
		.rp_ready              (vroom_0_avalon_master_limiter_rsp_src_ready)                                    //          .ready
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (105),
		.PKT_ORI_BURST_SIZE_L      (103),
		.PKT_RESPONSE_STATUS_H     (102),
		.PKT_RESPONSE_STATUS_L     (101),
		.PKT_BURST_SIZE_H          (84),
		.PKT_BURST_SIZE_L          (82),
		.PKT_TRANS_LOCK            (72),
		.PKT_BEGIN_BURST           (89),
		.PKT_PROTECTION_H          (96),
		.PKT_PROTECTION_L          (94),
		.PKT_BURSTWRAP_H           (81),
		.PKT_BURSTWRAP_L           (81),
		.PKT_BYTE_CNT_H            (80),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (91),
		.PKT_SRC_ID_L              (91),
		.PKT_DEST_ID_H             (92),
		.PKT_DEST_ID_L             (92),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (106),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) rom_s1_agent (
		.clk                     (pll_0_outclk0_clk),                              //             clk.clk
		.reset                   (VROOM_0_reset_sink_reset_bridge_in_reset_reset), //       clk_reset.reset
		.m0_address              (rom_s1_agent_m0_address),                        //              m0.address
		.m0_burstcount           (rom_s1_agent_m0_burstcount),                     //                .burstcount
		.m0_byteenable           (rom_s1_agent_m0_byteenable),                     //                .byteenable
		.m0_debugaccess          (rom_s1_agent_m0_debugaccess),                    //                .debugaccess
		.m0_lock                 (rom_s1_agent_m0_lock),                           //                .lock
		.m0_readdata             (rom_s1_agent_m0_readdata),                       //                .readdata
		.m0_readdatavalid        (rom_s1_agent_m0_readdatavalid),                  //                .readdatavalid
		.m0_read                 (rom_s1_agent_m0_read),                           //                .read
		.m0_waitrequest          (rom_s1_agent_m0_waitrequest),                    //                .waitrequest
		.m0_writedata            (rom_s1_agent_m0_writedata),                      //                .writedata
		.m0_write                (rom_s1_agent_m0_write),                          //                .write
		.rp_endofpacket          (rom_s1_agent_rp_endofpacket),                    //              rp.endofpacket
		.rp_ready                (rom_s1_agent_rp_ready),                          //                .ready
		.rp_valid                (rom_s1_agent_rp_valid),                          //                .valid
		.rp_data                 (rom_s1_agent_rp_data),                           //                .data
		.rp_startofpacket        (rom_s1_agent_rp_startofpacket),                  //                .startofpacket
		.cp_ready                (rom_s1_burst_adapter_source0_ready),             //              cp.ready
		.cp_valid                (rom_s1_burst_adapter_source0_valid),             //                .valid
		.cp_data                 (rom_s1_burst_adapter_source0_data),              //                .data
		.cp_startofpacket        (rom_s1_burst_adapter_source0_startofpacket),     //                .startofpacket
		.cp_endofpacket          (rom_s1_burst_adapter_source0_endofpacket),       //                .endofpacket
		.cp_channel              (rom_s1_burst_adapter_source0_channel),           //                .channel
		.rf_sink_ready           (rom_s1_agent_rsp_fifo_out_ready),                //         rf_sink.ready
		.rf_sink_valid           (rom_s1_agent_rsp_fifo_out_valid),                //                .valid
		.rf_sink_startofpacket   (rom_s1_agent_rsp_fifo_out_startofpacket),        //                .startofpacket
		.rf_sink_endofpacket     (rom_s1_agent_rsp_fifo_out_endofpacket),          //                .endofpacket
		.rf_sink_data            (rom_s1_agent_rsp_fifo_out_data),                 //                .data
		.rf_source_ready         (rom_s1_agent_rf_source_ready),                   //       rf_source.ready
		.rf_source_valid         (rom_s1_agent_rf_source_valid),                   //                .valid
		.rf_source_startofpacket (rom_s1_agent_rf_source_startofpacket),           //                .startofpacket
		.rf_source_endofpacket   (rom_s1_agent_rf_source_endofpacket),             //                .endofpacket
		.rf_source_data          (rom_s1_agent_rf_source_data),                    //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                  // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                  //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                   //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                  //                .error
		.rdata_fifo_src_ready    (rom_s1_agent_rdata_fifo_src_ready),              //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (rom_s1_agent_rdata_fifo_src_valid),              //                .valid
		.rdata_fifo_src_data     (rom_s1_agent_rdata_fifo_src_data),               //                .data
		.m0_response             (2'b00),                                          //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                            //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (107),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) rom_s1_agent_rsp_fifo (
		.clk               (pll_0_outclk0_clk),                              //       clk.clk
		.reset             (VROOM_0_reset_sink_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (rom_s1_agent_rf_source_data),                    //        in.data
		.in_valid          (rom_s1_agent_rf_source_valid),                   //          .valid
		.in_ready          (rom_s1_agent_rf_source_ready),                   //          .ready
		.in_startofpacket  (rom_s1_agent_rf_source_startofpacket),           //          .startofpacket
		.in_endofpacket    (rom_s1_agent_rf_source_endofpacket),             //          .endofpacket
		.out_data          (rom_s1_agent_rsp_fifo_out_data),                 //       out.data
		.out_valid         (rom_s1_agent_rsp_fifo_out_valid),                //          .valid
		.out_ready         (rom_s1_agent_rsp_fifo_out_ready),                //          .ready
		.out_startofpacket (rom_s1_agent_rsp_fifo_out_startofpacket),        //          .startofpacket
		.out_endofpacket   (rom_s1_agent_rsp_fifo_out_endofpacket),          //          .endofpacket
		.csr_address       (2'b00),                                          // (terminated)
		.csr_read          (1'b0),                                           // (terminated)
		.csr_write         (1'b0),                                           // (terminated)
		.csr_readdata      (),                                               // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),           // (terminated)
		.almost_full_data  (),                                               // (terminated)
		.almost_empty_data (),                                               // (terminated)
		.in_empty          (1'b0),                                           // (terminated)
		.out_empty         (),                                               // (terminated)
		.in_error          (1'b0),                                           // (terminated)
		.out_error         (),                                               // (terminated)
		.in_channel        (1'b0),                                           // (terminated)
		.out_channel       ()                                                // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (105),
		.PKT_ORI_BURST_SIZE_L      (103),
		.PKT_RESPONSE_STATUS_H     (102),
		.PKT_RESPONSE_STATUS_L     (101),
		.PKT_BURST_SIZE_H          (84),
		.PKT_BURST_SIZE_L          (82),
		.PKT_TRANS_LOCK            (72),
		.PKT_BEGIN_BURST           (89),
		.PKT_PROTECTION_H          (96),
		.PKT_PROTECTION_L          (94),
		.PKT_BURSTWRAP_H           (81),
		.PKT_BURSTWRAP_L           (81),
		.PKT_BYTE_CNT_H            (80),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (91),
		.PKT_SRC_ID_L              (91),
		.PKT_DEST_ID_H             (92),
		.PKT_DEST_ID_L             (92),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (106),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) ram_s1_agent (
		.clk                     (pll_0_outclk0_clk),                              //             clk.clk
		.reset                   (VROOM_0_reset_sink_reset_bridge_in_reset_reset), //       clk_reset.reset
		.m0_address              (ram_s1_agent_m0_address),                        //              m0.address
		.m0_burstcount           (ram_s1_agent_m0_burstcount),                     //                .burstcount
		.m0_byteenable           (ram_s1_agent_m0_byteenable),                     //                .byteenable
		.m0_debugaccess          (ram_s1_agent_m0_debugaccess),                    //                .debugaccess
		.m0_lock                 (ram_s1_agent_m0_lock),                           //                .lock
		.m0_readdata             (ram_s1_agent_m0_readdata),                       //                .readdata
		.m0_readdatavalid        (ram_s1_agent_m0_readdatavalid),                  //                .readdatavalid
		.m0_read                 (ram_s1_agent_m0_read),                           //                .read
		.m0_waitrequest          (ram_s1_agent_m0_waitrequest),                    //                .waitrequest
		.m0_writedata            (ram_s1_agent_m0_writedata),                      //                .writedata
		.m0_write                (ram_s1_agent_m0_write),                          //                .write
		.rp_endofpacket          (ram_s1_agent_rp_endofpacket),                    //              rp.endofpacket
		.rp_ready                (ram_s1_agent_rp_ready),                          //                .ready
		.rp_valid                (ram_s1_agent_rp_valid),                          //                .valid
		.rp_data                 (ram_s1_agent_rp_data),                           //                .data
		.rp_startofpacket        (ram_s1_agent_rp_startofpacket),                  //                .startofpacket
		.cp_ready                (ram_s1_burst_adapter_source0_ready),             //              cp.ready
		.cp_valid                (ram_s1_burst_adapter_source0_valid),             //                .valid
		.cp_data                 (ram_s1_burst_adapter_source0_data),              //                .data
		.cp_startofpacket        (ram_s1_burst_adapter_source0_startofpacket),     //                .startofpacket
		.cp_endofpacket          (ram_s1_burst_adapter_source0_endofpacket),       //                .endofpacket
		.cp_channel              (ram_s1_burst_adapter_source0_channel),           //                .channel
		.rf_sink_ready           (ram_s1_agent_rsp_fifo_out_ready),                //         rf_sink.ready
		.rf_sink_valid           (ram_s1_agent_rsp_fifo_out_valid),                //                .valid
		.rf_sink_startofpacket   (ram_s1_agent_rsp_fifo_out_startofpacket),        //                .startofpacket
		.rf_sink_endofpacket     (ram_s1_agent_rsp_fifo_out_endofpacket),          //                .endofpacket
		.rf_sink_data            (ram_s1_agent_rsp_fifo_out_data),                 //                .data
		.rf_source_ready         (ram_s1_agent_rf_source_ready),                   //       rf_source.ready
		.rf_source_valid         (ram_s1_agent_rf_source_valid),                   //                .valid
		.rf_source_startofpacket (ram_s1_agent_rf_source_startofpacket),           //                .startofpacket
		.rf_source_endofpacket   (ram_s1_agent_rf_source_endofpacket),             //                .endofpacket
		.rf_source_data          (ram_s1_agent_rf_source_data),                    //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_001_out_0_ready),              // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_001_out_0_valid),              //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_001_out_0_data),               //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_001_out_0_error),              //                .error
		.rdata_fifo_src_ready    (ram_s1_agent_rdata_fifo_src_ready),              //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (ram_s1_agent_rdata_fifo_src_valid),              //                .valid
		.rdata_fifo_src_data     (ram_s1_agent_rdata_fifo_src_data),               //                .data
		.m0_response             (2'b00),                                          //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                            //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (107),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) ram_s1_agent_rsp_fifo (
		.clk               (pll_0_outclk0_clk),                              //       clk.clk
		.reset             (VROOM_0_reset_sink_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (ram_s1_agent_rf_source_data),                    //        in.data
		.in_valid          (ram_s1_agent_rf_source_valid),                   //          .valid
		.in_ready          (ram_s1_agent_rf_source_ready),                   //          .ready
		.in_startofpacket  (ram_s1_agent_rf_source_startofpacket),           //          .startofpacket
		.in_endofpacket    (ram_s1_agent_rf_source_endofpacket),             //          .endofpacket
		.out_data          (ram_s1_agent_rsp_fifo_out_data),                 //       out.data
		.out_valid         (ram_s1_agent_rsp_fifo_out_valid),                //          .valid
		.out_ready         (ram_s1_agent_rsp_fifo_out_ready),                //          .ready
		.out_startofpacket (ram_s1_agent_rsp_fifo_out_startofpacket),        //          .startofpacket
		.out_endofpacket   (ram_s1_agent_rsp_fifo_out_endofpacket),          //          .endofpacket
		.csr_address       (2'b00),                                          // (terminated)
		.csr_read          (1'b0),                                           // (terminated)
		.csr_write         (1'b0),                                           // (terminated)
		.csr_readdata      (),                                               // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),           // (terminated)
		.almost_full_data  (),                                               // (terminated)
		.almost_empty_data (),                                               // (terminated)
		.in_empty          (1'b0),                                           // (terminated)
		.out_empty         (),                                               // (terminated)
		.in_error          (1'b0),                                           // (terminated)
		.out_error         (),                                               // (terminated)
		.in_channel        (1'b0),                                           // (terminated)
		.out_channel       ()                                                // (terminated)
	);

	vroom_system_mm_interconnect_0_router router (
		.sink_ready         (vroom_0_avalon_master_agent_cp_ready),           //      sink.ready
		.sink_valid         (vroom_0_avalon_master_agent_cp_valid),           //          .valid
		.sink_data          (vroom_0_avalon_master_agent_cp_data),            //          .data
		.sink_startofpacket (vroom_0_avalon_master_agent_cp_startofpacket),   //          .startofpacket
		.sink_endofpacket   (vroom_0_avalon_master_agent_cp_endofpacket),     //          .endofpacket
		.clk                (pll_0_outclk0_clk),                              //       clk.clk
		.reset              (VROOM_0_reset_sink_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                               //       src.ready
		.src_valid          (router_src_valid),                               //          .valid
		.src_data           (router_src_data),                                //          .data
		.src_channel        (router_src_channel),                             //          .channel
		.src_startofpacket  (router_src_startofpacket),                       //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                          //          .endofpacket
	);

	vroom_system_mm_interconnect_0_router_001 router_001 (
		.sink_ready         (rom_s1_agent_rp_ready),                          //      sink.ready
		.sink_valid         (rom_s1_agent_rp_valid),                          //          .valid
		.sink_data          (rom_s1_agent_rp_data),                           //          .data
		.sink_startofpacket (rom_s1_agent_rp_startofpacket),                  //          .startofpacket
		.sink_endofpacket   (rom_s1_agent_rp_endofpacket),                    //          .endofpacket
		.clk                (pll_0_outclk0_clk),                              //       clk.clk
		.reset              (VROOM_0_reset_sink_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                           //       src.ready
		.src_valid          (router_001_src_valid),                           //          .valid
		.src_data           (router_001_src_data),                            //          .data
		.src_channel        (router_001_src_channel),                         //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                   //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                      //          .endofpacket
	);

	vroom_system_mm_interconnect_0_router_001 router_002 (
		.sink_ready         (ram_s1_agent_rp_ready),                          //      sink.ready
		.sink_valid         (ram_s1_agent_rp_valid),                          //          .valid
		.sink_data          (ram_s1_agent_rp_data),                           //          .data
		.sink_startofpacket (ram_s1_agent_rp_startofpacket),                  //          .startofpacket
		.sink_endofpacket   (ram_s1_agent_rp_endofpacket),                    //          .endofpacket
		.clk                (pll_0_outclk0_clk),                              //       clk.clk
		.reset              (VROOM_0_reset_sink_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_002_src_ready),                           //       src.ready
		.src_valid          (router_002_src_valid),                           //          .valid
		.src_data           (router_002_src_data),                            //          .data
		.src_channel        (router_002_src_channel),                         //          .channel
		.src_startofpacket  (router_002_src_startofpacket),                   //          .startofpacket
		.src_endofpacket    (router_002_src_endofpacket)                      //          .endofpacket
	);

	altera_merlin_traffic_limiter #(
		.PKT_DEST_ID_H             (92),
		.PKT_DEST_ID_L             (92),
		.PKT_SRC_ID_H              (91),
		.PKT_SRC_ID_L              (91),
		.PKT_BYTE_CNT_H            (80),
		.PKT_BYTE_CNT_L            (74),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.MAX_OUTSTANDING_RESPONSES (3),
		.PIPELINED                 (0),
		.ST_DATA_W                 (106),
		.ST_CHANNEL_W              (2),
		.VALID_WIDTH               (2),
		.ENFORCE_ORDER             (1),
		.PREVENT_HAZARDS           (0),
		.SUPPORTS_POSTED_WRITES    (1),
		.SUPPORTS_NONPOSTED_WRITES (0),
		.REORDER                   (0)
	) vroom_0_avalon_master_limiter (
		.clk                    (pll_0_outclk0_clk),                                   //       clk.clk
		.reset                  (VROOM_0_reset_sink_reset_bridge_in_reset_reset),      // clk_reset.reset
		.cmd_sink_ready         (router_src_ready),                                    //  cmd_sink.ready
		.cmd_sink_valid         (router_src_valid),                                    //          .valid
		.cmd_sink_data          (router_src_data),                                     //          .data
		.cmd_sink_channel       (router_src_channel),                                  //          .channel
		.cmd_sink_startofpacket (router_src_startofpacket),                            //          .startofpacket
		.cmd_sink_endofpacket   (router_src_endofpacket),                              //          .endofpacket
		.cmd_src_ready          (vroom_0_avalon_master_limiter_cmd_src_ready),         //   cmd_src.ready
		.cmd_src_data           (vroom_0_avalon_master_limiter_cmd_src_data),          //          .data
		.cmd_src_channel        (vroom_0_avalon_master_limiter_cmd_src_channel),       //          .channel
		.cmd_src_startofpacket  (vroom_0_avalon_master_limiter_cmd_src_startofpacket), //          .startofpacket
		.cmd_src_endofpacket    (vroom_0_avalon_master_limiter_cmd_src_endofpacket),   //          .endofpacket
		.rsp_sink_ready         (rsp_mux_src_ready),                                   //  rsp_sink.ready
		.rsp_sink_valid         (rsp_mux_src_valid),                                   //          .valid
		.rsp_sink_channel       (rsp_mux_src_channel),                                 //          .channel
		.rsp_sink_data          (rsp_mux_src_data),                                    //          .data
		.rsp_sink_startofpacket (rsp_mux_src_startofpacket),                           //          .startofpacket
		.rsp_sink_endofpacket   (rsp_mux_src_endofpacket),                             //          .endofpacket
		.rsp_src_ready          (vroom_0_avalon_master_limiter_rsp_src_ready),         //   rsp_src.ready
		.rsp_src_valid          (vroom_0_avalon_master_limiter_rsp_src_valid),         //          .valid
		.rsp_src_data           (vroom_0_avalon_master_limiter_rsp_src_data),          //          .data
		.rsp_src_channel        (vroom_0_avalon_master_limiter_rsp_src_channel),       //          .channel
		.rsp_src_startofpacket  (vroom_0_avalon_master_limiter_rsp_src_startofpacket), //          .startofpacket
		.rsp_src_endofpacket    (vroom_0_avalon_master_limiter_rsp_src_endofpacket),   //          .endofpacket
		.cmd_src_valid          (vroom_0_avalon_master_limiter_cmd_valid_data)         // cmd_valid.data
	);

	altera_merlin_burst_adapter #(
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_BEGIN_BURST           (89),
		.PKT_BYTE_CNT_H            (80),
		.PKT_BYTE_CNT_L            (74),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_BURST_SIZE_H          (84),
		.PKT_BURST_SIZE_L          (82),
		.PKT_BURST_TYPE_H          (86),
		.PKT_BURST_TYPE_L          (85),
		.PKT_BURSTWRAP_H           (81),
		.PKT_BURSTWRAP_L           (81),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (0),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (106),
		.ST_CHANNEL_W              (2),
		.OUT_BYTE_CNT_H            (76),
		.OUT_BURSTWRAP_H           (81),
		.COMPRESSED_READ_SUPPORT   (1),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.INCOMPLETE_WRAP_SUPPORT   (0),
		.BURSTWRAP_CONST_MASK      (1),
		.BURSTWRAP_CONST_VALUE     (1),
		.ADAPTER_VERSION           ("13.1")
	) rom_s1_burst_adapter (
		.clk                   (pll_0_outclk0_clk),                              //       cr0.clk
		.reset                 (VROOM_0_reset_sink_reset_bridge_in_reset_reset), // cr0_reset.reset
		.sink0_valid           (cmd_mux_src_valid),                              //     sink0.valid
		.sink0_data            (cmd_mux_src_data),                               //          .data
		.sink0_channel         (cmd_mux_src_channel),                            //          .channel
		.sink0_startofpacket   (cmd_mux_src_startofpacket),                      //          .startofpacket
		.sink0_endofpacket     (cmd_mux_src_endofpacket),                        //          .endofpacket
		.sink0_ready           (cmd_mux_src_ready),                              //          .ready
		.source0_valid         (rom_s1_burst_adapter_source0_valid),             //   source0.valid
		.source0_data          (rom_s1_burst_adapter_source0_data),              //          .data
		.source0_channel       (rom_s1_burst_adapter_source0_channel),           //          .channel
		.source0_startofpacket (rom_s1_burst_adapter_source0_startofpacket),     //          .startofpacket
		.source0_endofpacket   (rom_s1_burst_adapter_source0_endofpacket),       //          .endofpacket
		.source0_ready         (rom_s1_burst_adapter_source0_ready)              //          .ready
	);

	altera_merlin_burst_adapter #(
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_BEGIN_BURST           (89),
		.PKT_BYTE_CNT_H            (80),
		.PKT_BYTE_CNT_L            (74),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_BURST_SIZE_H          (84),
		.PKT_BURST_SIZE_L          (82),
		.PKT_BURST_TYPE_H          (86),
		.PKT_BURST_TYPE_L          (85),
		.PKT_BURSTWRAP_H           (81),
		.PKT_BURSTWRAP_L           (81),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (0),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (106),
		.ST_CHANNEL_W              (2),
		.OUT_BYTE_CNT_H            (76),
		.OUT_BURSTWRAP_H           (81),
		.COMPRESSED_READ_SUPPORT   (1),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.INCOMPLETE_WRAP_SUPPORT   (0),
		.BURSTWRAP_CONST_MASK      (1),
		.BURSTWRAP_CONST_VALUE     (1),
		.ADAPTER_VERSION           ("13.1")
	) ram_s1_burst_adapter (
		.clk                   (pll_0_outclk0_clk),                              //       cr0.clk
		.reset                 (VROOM_0_reset_sink_reset_bridge_in_reset_reset), // cr0_reset.reset
		.sink0_valid           (cmd_mux_001_src_valid),                          //     sink0.valid
		.sink0_data            (cmd_mux_001_src_data),                           //          .data
		.sink0_channel         (cmd_mux_001_src_channel),                        //          .channel
		.sink0_startofpacket   (cmd_mux_001_src_startofpacket),                  //          .startofpacket
		.sink0_endofpacket     (cmd_mux_001_src_endofpacket),                    //          .endofpacket
		.sink0_ready           (cmd_mux_001_src_ready),                          //          .ready
		.source0_valid         (ram_s1_burst_adapter_source0_valid),             //   source0.valid
		.source0_data          (ram_s1_burst_adapter_source0_data),              //          .data
		.source0_channel       (ram_s1_burst_adapter_source0_channel),           //          .channel
		.source0_startofpacket (ram_s1_burst_adapter_source0_startofpacket),     //          .startofpacket
		.source0_endofpacket   (ram_s1_burst_adapter_source0_endofpacket),       //          .endofpacket
		.source0_ready         (ram_s1_burst_adapter_source0_ready)              //          .ready
	);

	vroom_system_mm_interconnect_0_cmd_demux cmd_demux (
		.clk                (pll_0_outclk0_clk),                                   //        clk.clk
		.reset              (VROOM_0_reset_sink_reset_bridge_in_reset_reset),      //  clk_reset.reset
		.sink_ready         (vroom_0_avalon_master_limiter_cmd_src_ready),         //       sink.ready
		.sink_channel       (vroom_0_avalon_master_limiter_cmd_src_channel),       //           .channel
		.sink_data          (vroom_0_avalon_master_limiter_cmd_src_data),          //           .data
		.sink_startofpacket (vroom_0_avalon_master_limiter_cmd_src_startofpacket), //           .startofpacket
		.sink_endofpacket   (vroom_0_avalon_master_limiter_cmd_src_endofpacket),   //           .endofpacket
		.sink_valid         (vroom_0_avalon_master_limiter_cmd_valid_data),        // sink_valid.data
		.src0_ready         (cmd_demux_src0_ready),                                //       src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                //           .valid
		.src0_data          (cmd_demux_src0_data),                                 //           .data
		.src0_channel       (cmd_demux_src0_channel),                              //           .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                        //           .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket),                          //           .endofpacket
		.src1_ready         (cmd_demux_src1_ready),                                //       src1.ready
		.src1_valid         (cmd_demux_src1_valid),                                //           .valid
		.src1_data          (cmd_demux_src1_data),                                 //           .data
		.src1_channel       (cmd_demux_src1_channel),                              //           .channel
		.src1_startofpacket (cmd_demux_src1_startofpacket),                        //           .startofpacket
		.src1_endofpacket   (cmd_demux_src1_endofpacket)                           //           .endofpacket
	);

	vroom_system_mm_interconnect_0_cmd_mux cmd_mux (
		.clk                 (pll_0_outclk0_clk),                              //       clk.clk
		.reset               (VROOM_0_reset_sink_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                              //       src.ready
		.src_valid           (cmd_mux_src_valid),                              //          .valid
		.src_data            (cmd_mux_src_data),                               //          .data
		.src_channel         (cmd_mux_src_channel),                            //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                      //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                        //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                           //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                           //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                         //          .channel
		.sink0_data          (cmd_demux_src0_data),                            //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                   //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                      //          .endofpacket
	);

	vroom_system_mm_interconnect_0_cmd_mux cmd_mux_001 (
		.clk                 (pll_0_outclk0_clk),                              //       clk.clk
		.reset               (VROOM_0_reset_sink_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_001_src_ready),                          //       src.ready
		.src_valid           (cmd_mux_001_src_valid),                          //          .valid
		.src_data            (cmd_mux_001_src_data),                           //          .data
		.src_channel         (cmd_mux_001_src_channel),                        //          .channel
		.src_startofpacket   (cmd_mux_001_src_startofpacket),                  //          .startofpacket
		.src_endofpacket     (cmd_mux_001_src_endofpacket),                    //          .endofpacket
		.sink0_ready         (cmd_demux_src1_ready),                           //     sink0.ready
		.sink0_valid         (cmd_demux_src1_valid),                           //          .valid
		.sink0_channel       (cmd_demux_src1_channel),                         //          .channel
		.sink0_data          (cmd_demux_src1_data),                            //          .data
		.sink0_startofpacket (cmd_demux_src1_startofpacket),                   //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src1_endofpacket)                      //          .endofpacket
	);

	vroom_system_mm_interconnect_0_rsp_demux rsp_demux (
		.clk                (pll_0_outclk0_clk),                              //       clk.clk
		.reset              (VROOM_0_reset_sink_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                           //      sink.ready
		.sink_channel       (router_001_src_channel),                         //          .channel
		.sink_data          (router_001_src_data),                            //          .data
		.sink_startofpacket (router_001_src_startofpacket),                   //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                     //          .endofpacket
		.sink_valid         (router_001_src_valid),                           //          .valid
		.src0_ready         (rsp_demux_src0_ready),                           //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                           //          .valid
		.src0_data          (rsp_demux_src0_data),                            //          .data
		.src0_channel       (rsp_demux_src0_channel),                         //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                   //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                      //          .endofpacket
	);

	vroom_system_mm_interconnect_0_rsp_demux rsp_demux_001 (
		.clk                (pll_0_outclk0_clk),                              //       clk.clk
		.reset              (VROOM_0_reset_sink_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_002_src_ready),                           //      sink.ready
		.sink_channel       (router_002_src_channel),                         //          .channel
		.sink_data          (router_002_src_data),                            //          .data
		.sink_startofpacket (router_002_src_startofpacket),                   //          .startofpacket
		.sink_endofpacket   (router_002_src_endofpacket),                     //          .endofpacket
		.sink_valid         (router_002_src_valid),                           //          .valid
		.src0_ready         (rsp_demux_001_src0_ready),                       //      src0.ready
		.src0_valid         (rsp_demux_001_src0_valid),                       //          .valid
		.src0_data          (rsp_demux_001_src0_data),                        //          .data
		.src0_channel       (rsp_demux_001_src0_channel),                     //          .channel
		.src0_startofpacket (rsp_demux_001_src0_startofpacket),               //          .startofpacket
		.src0_endofpacket   (rsp_demux_001_src0_endofpacket)                  //          .endofpacket
	);

	vroom_system_mm_interconnect_0_rsp_mux rsp_mux (
		.clk                 (pll_0_outclk0_clk),                              //       clk.clk
		.reset               (VROOM_0_reset_sink_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                              //       src.ready
		.src_valid           (rsp_mux_src_valid),                              //          .valid
		.src_data            (rsp_mux_src_data),                               //          .data
		.src_channel         (rsp_mux_src_channel),                            //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                      //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                        //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                           //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                           //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                         //          .channel
		.sink0_data          (rsp_demux_src0_data),                            //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                   //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket),                     //          .endofpacket
		.sink1_ready         (rsp_demux_001_src0_ready),                       //     sink1.ready
		.sink1_valid         (rsp_demux_001_src0_valid),                       //          .valid
		.sink1_channel       (rsp_demux_001_src0_channel),                     //          .channel
		.sink1_data          (rsp_demux_001_src0_data),                        //          .data
		.sink1_startofpacket (rsp_demux_001_src0_startofpacket),               //          .startofpacket
		.sink1_endofpacket   (rsp_demux_001_src0_endofpacket)                  //          .endofpacket
	);

	vroom_system_mm_interconnect_0_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (pll_0_outclk0_clk),                              // in_clk_0.clk
		.in_rst_0_reset (VROOM_0_reset_sink_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (rom_s1_agent_rdata_fifo_src_data),               //     in_0.data
		.in_0_valid     (rom_s1_agent_rdata_fifo_src_valid),              //         .valid
		.in_0_ready     (rom_s1_agent_rdata_fifo_src_ready),              //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                   //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                  //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                  //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                   //         .error
	);

	vroom_system_mm_interconnect_0_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter_001 (
		.in_clk_0_clk   (pll_0_outclk0_clk),                              // in_clk_0.clk
		.in_rst_0_reset (VROOM_0_reset_sink_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (ram_s1_agent_rdata_fifo_src_data),               //     in_0.data
		.in_0_valid     (ram_s1_agent_rdata_fifo_src_valid),              //         .valid
		.in_0_ready     (ram_s1_agent_rdata_fifo_src_ready),              //         .ready
		.out_0_data     (avalon_st_adapter_001_out_0_data),               //    out_0.data
		.out_0_valid    (avalon_st_adapter_001_out_0_valid),              //         .valid
		.out_0_ready    (avalon_st_adapter_001_out_0_ready),              //         .ready
		.out_0_error    (avalon_st_adapter_001_out_0_error)               //         .error
	);

endmodule
